version: '3.8'
services:
  # MySQL Database Service
  db:
    image: mysql:5.7
    volumes:
      - karo_data:/var/lib/mysql
    networks:
      - wp_network
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: wordpresspassword
  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    networks:
      - wp_network
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
  # WordPress Service
  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    ports:
      - "8000:80"
    networks:
      - wp_network
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: wordpresspassword
      WORDPRESS_DB_NAME: wordpress
# Volumes for Persistent Storage
volumes:
  karo_data:
  wordpress_data:
# Custom Network
networks:
  wp_network:
